"""
互动率分析使用示例
演示如何使用新的互动率分析功能
"""
import sys
from datetime import datetime, timedelta
from src.kol_analyzer import KeywordKOLAnalyzer
import logging

# 配置日志
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)

print("=" * 80)
print("YouTube KOL 互动率分析示例")
print("=" * 80)
print()

# 创建分析器
analyzer = KeywordKOLAnalyzer(logger=logger)

print("📊 功能说明:")
print("-" * 80)
print("1. 获取关键词相关的所有视频")
print("2. 分析每个频道的视频表现")
print("3. 计算每个视频的互动率 = (点赞数 + 评论数) / 播放量 × 100%")
print("4. 计算频道最近10条视频的平均互动率")
print("5. 按频道汇总，生成详细的 Excel 报表")
print()

print("🎯 分析目标:")
print("-" * 80)
print("找出以下特征的优质 KOL:")
print("  ✓ 粉丝数量适中（50K - 500K）")
print("  ✓ 互动率高（> 5%）")
print("  ✓ 平均播放量稳定（> 10K）")
print()

# 示例 1: 快速分析（仅使用数据库数据）
print("\n" + "=" * 80)
print("示例 1: 快速分析（使用数据库现有数据）")
print("=" * 80)
print()
print("说明: 仅分析数据库中已有的视频数据，不消耗 API 配额")
print("适用场景: 快速查看历史数据、初步筛选")
print()
print("命令: python analyze_keyword_kol.py \"python教程\"")
print()

# 示例 2: 完整分析（获取最新数据）
print("\n" + "=" * 80)
print("示例 2: 完整分析（获取每个频道的最新10个视频）")
print("=" * 80)
print()
print("说明: 为每个频道获取最新的10个视频，包含最新的互动数据")
print("适用场景: 需要最新数据、准备合作决策")
print("注意: 会消耗 API 配额（每个频道约 2-3 次调用）")
print()
print("命令: python analyze_keyword_kol.py \"python教程\" --get-latest-videos")
print()

# 示例 3: 指定时间范围
print("\n" + "=" * 80)
print("示例 3: 分析指定时间范围的视频")
print("=" * 80)
print()
print("说明: 只分析 2024 年发布的视频")
print("适用场景: 分析最近的趋势、排除老旧数据")
print()
print("命令: python analyze_keyword_kol.py \"python教程\" --start-year 2024 --get-latest-videos")
print()

# 数据解读示例
print("\n" + "=" * 80)
print("📊 Excel 报表解读")
print("=" * 80)
print()
print("频道概览表 - 关键列说明:")
print("-" * 80)
print("1. 频道名称 - KOL 的频道名")
print("2. 粉丝数 - 订阅者数量，反映影响力")
print("3. 相关视频数 - 包含关键词的视频数量")
print("4. 平均播放量 - 关键词相关视频的平均播放")
print("5. 最新10视频平均播放 - 最近视频的表现")
print("6. ⭐ 最新10视频平均互动率 - 新增！观众参与度指标")
print()
print("视频详情表 - 关键列说明:")
print("-" * 80)
print("1. 播放量 - 视频观看次数")
print("2. ⭐ 点赞数 - 新增！观众点赞数")
print("3. ⭐ 评论数 - 新增！观众评论数")
print("4. ⭐ 互动率(%) - 新增！综合参与度指标")
print("5. 发布时间 - 视频发布日期")
print()

# 筛选建议
print("\n" + "=" * 80)
print("🎯 优质 KOL 筛选建议")
print("=" * 80)
print()
print("第一步: 按粉丝数筛选")
print("  推荐范围: 50K - 500K")
print("  理由: 腰部 KOL 性价比高，粉丝忠诚度通常较高")
print()
print("第二步: 按互动率筛选")
print("  最低标准: > 3%")
print("  推荐标准: > 5%")
print("  优秀标准: > 10%")
print("  理由: 高互动率说明观众真正喜欢内容")
print()
print("第三步: 按平均播放量筛选")
print("  最低标准: > 10K")
print("  理由: 保证实际曝光量")
print()
print("第四步: 人工审核")
print("  - 查看频道主页，确认内容风格匹配")
print("  - 看几个热门视频，评估内容质量")
print("  - 查看评论区，了解粉丝画像")
print()

# 互动率标准
print("\n" + "=" * 80)
print("📊 互动率参考标准")
print("=" * 80)
print()
print("行业基准:")
print("  🔥 > 10%  - 优秀，粉丝高度活跃")
print("  ✅ 5-10%  - 良好，内容受欢迎")
print("  ⚠️ 2-5%   - 一般，有提升空间")
print("  ❌ < 2%   - 较低，需要优化")
print()
print("不同类型内容的典型互动率:")
print("  - 教程类: 3-8%")
print("  - 娱乐类: 5-15%")
print("  - 新闻类: 1-3%")
print("  - 评测类: 4-10%")
print()

# 实际案例
print("\n" + "=" * 80)
print("💡 实际分析案例")
print("=" * 80)
print()
print("假设分析「python教程」关键词，找到 3 个频道:")
print()
print("频道 A:")
print("  粉丝数: 800K")
print("  平均播放: 50K")
print("  互动率: 2.1%")
print("  评估: ❌ 虽然粉丝多，但互动率低，观众参与度不高")
print()
print("频道 B:")
print("  粉丝数: 150K")
print("  平均播放: 15K")
print("  互动率: 7.8%")
print("  评估: ✅ 粉丝数适中，互动率高，性价比好！")
print()
print("频道 C:")
print("  粉丝数: 30K")
print("  平均播放: 5K")
print("  互动率: 12.5%")
print("  评估: ⚠️ 互动率很高，但体量太小，影响力有限")
print()
print("结论: 频道 B 是最佳合作对象")
print()

print("=" * 80)
print("🎉 准备好开始分析了吗？")
print("=" * 80)
print()
print("推荐步骤:")
print("1. 运行 GUI: python gui_with_kol_analysis.py")
print("2. 点击 'KOL Analysis' 按钮")
print("3. 输入关键词，勾选 'Get Latest Videos'")
print("4. 等待分析完成，打开 Excel 文件")
print("5. 按照上述标准筛选优质 KOL")
print()
print("详细文档: ENGAGEMENT_RATE_GUIDE.md")
print("=" * 80)
